SET PAGESIZE 200
SET LINESIZE 220
SET FEEDBACK OFF
COLUMN NRO_INT_PARAMETRO_MARCO FORMAT 9999
COLUMN TXT_CHAVE   FORMAT A40
COLUMN TXT_VALOR   FORMAT A60
COLUMN TXT_NOTA    FORMAT A60

SELECT NRO_INT_PARAMETRO_MARCO, TXT_CHAVE, TXT_VALOR, IND_ATIVO
FROM CBM_PARAMETRO_MARCO
ORDER BY NRO_INT_PARAMETRO_MARCO;

-- Distribuição de TP_STATUS em CBM_USUARIO
SELECT TP_STATUS, COUNT(*) AS QTD FROM CBM_USUARIO GROUP BY TP_STATUS ORDER BY 2 DESC;

EXIT;
