SET PAGESIZE 100 LINESIZE 200 FEEDBACK OFF

-- Quantos COD_LICENCIAMENTO são duplicados
SELECT COUNT(*) AS TOTAL_DUPLICADOS
FROM (
  SELECT COD_LICENCIAMENTO
  FROM CBM_LICENCIAMENTO
  WHERE COD_LICENCIAMENTO IS NOT NULL
  GROUP BY COD_LICENCIAMENTO
  HAVING COUNT(*) > 1
);

-- Amostra dos duplicados
SELECT COD_LICENCIAMENTO, COUNT(*) AS QTD,
       MIN(NRO_INT_LICENCIAMENTO) AS ID_MAIS_ANTIGO,
       MAX(NRO_INT_LICENCIAMENTO) AS ID_MAIS_RECENTE,
       MIN(TP_SITUACAO) KEEP (DENSE_RANK LAST ORDER BY NRO_INT_LICENCIAMENTO) AS SITUACAO_RECENTE
FROM CBM_LICENCIAMENTO
WHERE COD_LICENCIAMENTO IS NOT NULL
GROUP BY COD_LICENCIAMENTO
HAVING COUNT(*) > 1
ORDER BY 2 DESC
FETCH FIRST 20 ROWS ONLY;

-- Quantos licenciamentos têm COD_LICENCIAMENTO NULL
SELECT COUNT(*) AS SEM_NUMERO FROM CBM_LICENCIAMENTO WHERE COD_LICENCIAMENTO IS NULL;

EXIT;
