-- ============================================================
-- migrar-producao-v2.sql  —  SOL CBM-RS
-- Versão 2: mapeamentos corrigidos após diagnóstico PASSO 0
--
-- Execução:
--   sqlplus P_CBM_SOLCBM_AD/GuiGui1267@//localhost:1521/XEPDB1 @migrar-producao-v2.sql
--
-- O script limpa os dados de teste do schema SOL antes de migrar.
-- COMMIT só ocorre ao final — revise os contadores antes de confirmar.
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 200
SET LINESIZE 200
SET FEEDBACK ON

-- ============================================================
-- PASSO 0 — Inspecionar colunas reais de CBM_PARAMETRO_MARCO
-- ============================================================
PROMPT === Colunas de CBM_PARAMETRO_MARCO ===
SELECT column_name, data_type, data_length FROM user_tab_columns WHERE table_name = 'CBM_PARAMETRO_MARCO' ORDER BY column_id;

-- ============================================================
-- PASSO 1 — Limpar dados de teste do schema SOL
--           (ordem inversa das FKs)
-- ============================================================
PROMPT === PASSO 1: Limpando dados de teste do schema SOL ===

DELETE FROM SOL.ARQUIVO_ED;
DELETE FROM SOL.MARCO_PROCESSO;
DELETE FROM SOL.BOLETO;
DELETE FROM SOL.LICENCIAMENTO;
DELETE FROM SOL.ENDERECO;
DELETE FROM SOL.USUARIO;
DELETE FROM SOL.ROTINA_EXECUCAO;

DECLARE v NUMBER;
BEGIN
  SELECT COUNT(*) INTO v FROM SOL.USUARIO; DBMS_OUTPUT.PUT_LINE('USUARIO restante: ' || v);
  SELECT COUNT(*) INTO v FROM SOL.LICENCIAMENTO; DBMS_OUTPUT.PUT_LINE('LICENCIAMENTO restante: ' || v);
END;
/

-- ============================================================
-- PASSO 2 — Migrar USUARIO
-- ============================================================
PROMPT === PASSO 2: Migrando USUARIO ===

INSERT INTO SOL.USUARIO (
    ID_USUARIO, CPF, NOME, EMAIL, TELEFONE,
    TIPO_USUARIO, STATUS_CADASTRO, ATIVO,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    u.NRO_INT_USUARIO,
    SUBSTR(REGEXP_REPLACE(u.TXT_CPF, '[^0-9]', ''), 1, 11),
    SUBSTR(u.NOME_USUARIO, 1, 200),
    SUBSTR(u.TXT_EMAIL, 1, 200),
    SUBSTR(u.TXT_TELEFONE1, 1, 20),
    CASE
        WHEN EXISTS (
            SELECT 1 FROM CBM_RESPONSAVEL_TECNICO rt
            WHERE rt.NRO_INT_USUARIO = u.NRO_INT_USUARIO AND ROWNUM = 1
        ) THEN 'RT'
        ELSE 'CIDADAO'
    END,
    CASE u.TP_STATUS WHEN 1 THEN 'ATIVO' ELSE 'INCOMPLETO' END,
    'S',
    CAST(COALESCE(u.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(u.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_USUARIO u
WHERE u.TXT_EMAIL IS NOT NULL
  AND REGEXP_REPLACE(u.TXT_CPF, '[^0-9]', '') IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.USUARIO; DBMS_OUTPUT.PUT_LINE('USUARIO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 3 — Migrar ENDERECO
--           CEP NULL recebe '00000000' como placeholder
-- ============================================================
PROMPT === PASSO 3: Migrando ENDERECO ===

INSERT INTO SOL.ENDERECO (
    ID_ENDERECO, CEP, LOGRADOURO, NUMERO, COMPLEMENTO,
    BAIRRO, MUNICIPIO, UF, LATITUDE, LONGITUDE,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    loc.NRO_INT_LOCALIZACAO,
    COALESCE(SUBSTR(REGEXP_REPLACE(loc.TXT_CEP, '[^0-9]', ''), 1, 8), '00000000'),
    SUBSTR(el.TXT_LOGRADOURO, 1, 200),
    SUBSTR(TO_CHAR(el.NRO_IMOVEL), 1, 20),
    SUBSTR(loc.TXT_COMPLEMENTO, 1, 100),
    SUBSTR(COALESCE(loc.TXT_BAIRRO, 'NAO INFORMADO'), 1, 100),
    SUBSTR(el.TXT_CIDADE, 1, 100),
    SUBSTR(el.SIGLA_UF, 1, 2),
    loc.NRO_LATITUDE_MAPA,
    loc.NRO_LONGITUDE_MAPA,
    CAST(COALESCE(loc.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(loc.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_LICENCIAMENTO lic
JOIN CBM_LOCALIZACAO loc
    ON loc.NRO_INT_LOCALIZACAO = lic.NRO_INT_LOCALIZACAO
JOIN CBM_ENDERECO_LICENCIAMENTO el
    ON el.NRO_INT_ENDERECO_LICENCIAMENTO = loc.NRO_INT_ENDERECO_LICENCIAMENTO
WHERE lic.NRO_INT_LOCALIZACAO IS NOT NULL
  AND el.TXT_LOGRADOURO IS NOT NULL
  AND el.TXT_CIDADE IS NOT NULL
  AND el.SIGLA_UF IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.ENDERECO; DBMS_OUTPUT.PUT_LINE('ENDERECO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 4 — Migrar LICENCIAMENTO
--           Mapeamento completo de TP_SITUACAO → StatusLicenciamento
-- ============================================================
PROMPT === PASSO 4: Migrando LICENCIAMENTO ===

INSERT INTO SOL.LICENCIAMENTO (
    ID_LICENCIAMENTO, NUMERO_PPCI, TIPO, STATUS,
    ID_ENDERECO, ID_RESPONSAVEL_TECNICO, ID_RESPONSAVEL_USO,
    ISENTO_TAXA, ISENTO_TAXA_RENOVACAO, ATIVO,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    lic.NRO_INT_LICENCIAMENTO,
    SUBSTR(lic.COD_LICENCIAMENTO, 1, 20),
    CASE
        WHEN UPPER(lic.TP_LICENCIAMENTO) LIKE '%PSPCIM%' THEN 'PSPCIM'
        ELSE 'PPCI'
    END,
    CASE lic.TP_SITUACAO
        WHEN 'RASCUNHO'                     THEN 'RASCUNHO'
        WHEN 'AGUARDANDO_DISTRIBUICAO'      THEN 'ANALISE_PENDENTE'
        WHEN 'AGUARDANDO_ENDERECO'          THEN 'ANALISE_PENDENTE'
        WHEN 'ANALISE_ENDERECO_PENDENTE'    THEN 'ANALISE_PENDENTE'
        WHEN 'AGUARDANDO_ACEITE'            THEN 'ANALISE_PENDENTE'
        WHEN 'EM_ANALISE'                   THEN 'EM_ANALISE'
        WHEN 'ANALISE_INVIABILIDADE_PENDENTE' THEN 'EM_ANALISE'
        WHEN 'AGUARDANDO_CIENCIA'           THEN 'APROVADO_TAXA'
        WHEN 'AGUARDANDO_PAGAMENTO'         THEN 'AGUARDANDO_PAGAMENTO'
        WHEN 'AGUARDANDO_PAGAMENTO_VISTORIA' THEN 'AGUARDANDO_PAGAMENTO'
        WHEN 'AGUARDANDO_PAGAMENTO_RENOVACAO' THEN 'AGUARDANDO_PAGAMENTO'
        WHEN 'AGUARDANDO_PRPCI'             THEN 'PAGO'
        WHEN 'AGUARDANDO_ACEITE_PRPCI'      THEN 'PAGO'
        WHEN 'AGUARDA_DISTRIBUICAO_VISTORIA' THEN 'VISTORIA_PENDENTE'
        WHEN 'AGUARDANDO_ACEITE_VISTORIA'   THEN 'VISTORIA_PENDENTE'
        WHEN 'EM_VISTORIA'                  THEN 'EM_VISTORIA'
        WHEN 'EM_VISTORIA_RENOVACAO'        THEN 'EM_VISTORIA'
        WHEN 'AGUARDANDO_CIENCIA_CIV'       THEN 'APROVADO'
        WHEN 'CA'                           THEN 'APROVADO'
        WHEN 'CIV'                          THEN 'APROVADO'
        WHEN 'ALVARA_VIGENTE'               THEN 'APROVADO'
        WHEN 'NCA'                          THEN 'REPROVADO'
        WHEN 'RECURSO_EM_ANALISE_1_CIA'     THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_2_CIA'     THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_1_CIV'     THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_2_CIV'     THEN 'EM_RECURSO'
        WHEN 'EXTINGUIDO'                   THEN 'EXTINTO'
        WHEN 'AGUARDANDO_ACEITES_EXTINCAO'  THEN 'EXTINTO'
        WHEN 'ALVARA_VENCIDO'               THEN 'RENOVACAO_PENDENTE'
        WHEN 'AGUARDANDO_ACEITE_RENOVACAO'  THEN 'RENOVACAO_PENDENTE'
        WHEN 'AGUARDANDO_DISTRIBUICAO_RENOV' THEN 'RENOVACAO_PENDENTE'
        ELSE 'ANALISE_PENDENTE'
    END,
    loc.NRO_INT_LOCALIZACAO,
    (SELECT rt.NRO_INT_USUARIO FROM CBM_RESPONSAVEL_TECNICO rt
     WHERE rt.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
       AND rt.IND_ACEITE = 'S' AND ROWNUM = 1),
    (SELECT ru.NRO_INT_USUARIO FROM CBM_RESPONSAVEL_USO ru
     WHERE ru.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
       AND ru.IND_ACEITE = 'S' AND ROWNUM = 1),
    CASE lic.IND_ISENCAO WHEN 'S' THEN 'S' ELSE 'N' END,
    'N',
    'S',
    CAST(COALESCE(lic.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(lic.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_LICENCIAMENTO lic
JOIN CBM_LOCALIZACAO loc ON loc.NRO_INT_LOCALIZACAO = lic.NRO_INT_LOCALIZACAO
WHERE lic.NRO_INT_LOCALIZACAO IS NOT NULL
  AND EXISTS (SELECT 1 FROM SOL.ENDERECO e WHERE e.ID_ENDERECO = loc.NRO_INT_LOCALIZACAO);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.LICENCIAMENTO; DBMS_OUTPUT.PUT_LINE('LICENCIAMENTO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 5 — Migrar BOLETO
--           TP_SITUACAO: 0=CANCELADO  1=PENDENTE  2=PAGO
-- ============================================================
PROMPT === PASSO 5: Migrando BOLETO ===

INSERT INTO SOL.BOLETO (
    ID_BOLETO, NOSSO_NUMERO, CODIGO_BARRAS, LINHA_DIGITAVEL,
    VALOR, DT_EMISSAO, DT_VENCIMENTO, DT_PAGAMENTO,
    STATUS, ID_LICENCIAMENTO,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    b.NRO_INT_BOLETO,
    SUBSTR(TO_CHAR(b.NRO_NOSSO_NUMERO), 1, 20),
    SUBSTR(b.TXT_CODIGO_BARRAS, 1, 60),
    SUBSTR(b.TXT_LINHA_DIGITAVEL, 1, 60),
    b.VALOR_NOMINAL,
    b.DATA_EMISSAO,
    b.DATA_VENCIMENTO,
    b.DATA_PAGAMENTO,
    CASE b.TP_SITUACAO
        WHEN 0 THEN 'CANCELADO'
        WHEN 1 THEN 'PENDENTE'
        WHEN 2 THEN 'PAGO'
        ELSE 'PENDENTE'
    END,
    bl.NRO_INT_LICENCIAMENTO,
    CAST(COALESCE(b.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(b.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_BOLETO b
JOIN CBM_BOLETO_LICENCIAMENTO bl ON bl.NRO_INT_BOLETO = b.NRO_INT_BOLETO
WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = bl.NRO_INT_LICENCIAMENTO)
  AND b.VALOR_NOMINAL IS NOT NULL
  AND b.DATA_EMISSAO IS NOT NULL
  AND b.DATA_VENCIMENTO IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.BOLETO; DBMS_OUTPUT.PUT_LINE('BOLETO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 6 — Migrar MARCO_PROCESSO
--           ATENÇÃO: ajuste DSC_MARCO (ou nome real) após
--           ver o resultado do PASSO 0 (colunas do PARAMETRO_MARCO)
-- ============================================================
PROMPT === PASSO 6: Migrando MARCO_PROCESSO ===

INSERT INTO SOL.MARCO_PROCESSO (
    ID_MARCO_PROCESSO, TIPO_MARCO, OBSERVACAO,
    ID_LICENCIAMENTO, ID_USUARIO, DT_MARCO
)
SELECT
    lm.NRO_INT_LIC_MARCO,
    -- Mapeamento por NRO_INT_PARAMETRO_MARCO (ajuste conforme colunas reais)
    CASE lm.NRO_INT_PARAMETRO_MARCO
        WHEN 1  THEN 'SOLICITACAO'
        WHEN 2  THEN 'ANALISE_INICIADA'
        WHEN 3  THEN 'APROVACAO'
        WHEN 4  THEN 'REPROVACAO'
        WHEN 5  THEN 'VISTORIA'
        WHEN 6  THEN 'RECURSO'
        WHEN 7  THEN 'EXTINCAO'
        WHEN 8  THEN 'RENOVACAO'
        WHEN 9  THEN 'PAGAMENTO'
        WHEN 10 THEN 'NOTIFICACAO'
        ELSE 'OBSERVACAO'
    END,
    SUBSTR(lm.TXT_DESCRICAO || CASE WHEN lm.TXT_COMPLEMENTAR IS NOT NULL
           THEN ' | ' || lm.TXT_COMPLEMENTAR ELSE '' END, 1, 4000),
    lm.NRO_INT_LICENCIAMENTO,
    lm.NRO_INT_USUARIO_RESP,
    CAST(lm.DTH_MARCO AS DATE)
FROM CBM_LICENCIAMENTO_MARCO lm
WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = lm.NRO_INT_LICENCIAMENTO)
  AND lm.TXT_DESCRICAO IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.MARCO_PROCESSO; DBMS_OUTPUT.PUT_LINE('MARCO_PROCESSO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 7 — Migrar ARQUIVO_ED (PRPCI + APPCI)
--           TP_ARQUIVO: 0=cache/auxiliar  1=documento  2=consulta
-- ============================================================
PROMPT === PASSO 7: Migrando ARQUIVO_ED ===

INSERT INTO SOL.ARQUIVO_ED (
    ID_ARQUIVO_ED, NOME_ARQUIVO, IDENTIFICADOR_ALFRESCO,
    TIPO_ARQUIVO, ID_LICENCIAMENTO, DT_UPLOAD
)
SELECT NRO_INT_ARQUIVO, NOME_ARQUIVO, TXT_IDENTIFICADOR_ALFRESCO,
       TIPO_ARQUIVO, ID_LICENCIAMENTO, DT_UPLOAD
FROM (
    SELECT a.NRO_INT_ARQUIVO, SUBSTR(a.NOME_ARQUIVO, 1, 500) AS NOME_ARQUIVO,
           SUBSTR(a.TXT_IDENTIFICADOR_ALFRESCO, 1, 500) AS TXT_IDENTIFICADOR_ALFRESCO,
           'PRPCI' AS TIPO_ARQUIVO,
           p.NRO_INT_LICENCIAMENTO AS ID_LICENCIAMENTO,
           CAST(COALESCE(a.CTR_DTH_INC, SYSTIMESTAMP) AS DATE) AS DT_UPLOAD
    FROM CBM_PRPCI p
    JOIN CBM_ARQUIVO a ON a.NRO_INT_ARQUIVO = p.NRO_INT_ARQUIVO
    WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = p.NRO_INT_LICENCIAMENTO)
    UNION ALL
    SELECT a.NRO_INT_ARQUIVO, SUBSTR(a.NOME_ARQUIVO, 1, 500),
           SUBSTR(a.TXT_IDENTIFICADOR_ALFRESCO, 1, 500),
           'APPCI', ap.NRO_INT_LICENCIAMENTO,
           CAST(COALESCE(a.CTR_DTH_INC, SYSTIMESTAMP) AS DATE)
    FROM CBM_APPCI ap
    JOIN CBM_ARQUIVO a ON a.NRO_INT_ARQUIVO = ap.NRO_INT_ARQUIVO
    WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = ap.NRO_INT_LICENCIAMENTO)
) src
WHERE NOT EXISTS (SELECT 1 FROM SOL.ARQUIVO_ED ae WHERE ae.ID_ARQUIVO_ED = src.NRO_INT_ARQUIVO);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.ARQUIVO_ED; DBMS_OUTPUT.PUT_LINE('ARQUIVO_ED inserido: ' || v); END;
/

-- ============================================================
-- PASSO 8 — Migrar ROTINA_EXECUCAO
--           TP_SITUACAO: 0=EM_EXECUCAO  1=CONCLUIDA  2=ERRO
-- ============================================================
PROMPT === PASSO 8: Migrando ROTINA_EXECUCAO ===

INSERT INTO SOL.ROTINA_EXECUCAO (
    ID_ROTINA_EXECUCAO, TIPO_ROTINA,
    DTH_INICIO_EXECUCAO, DTH_FIM_EXECUCAO,
    DSC_SITUACAO, NR_ERROS, DSC_MENSAGEM_ERRO,
    DTH_CRIACAO
)
SELECT
    r.NRO_INT_ROTINA,
    SUBSTR(r.TXT_ROTINA, 1, 60),
    r.DTH_INICIO,
    r.DTH_FIM,
    CASE r.TP_SITUACAO
        WHEN 0 THEN 'EM_EXECUCAO'
        WHEN 1 THEN 'CONCLUIDA'
        WHEN 2 THEN 'ERRO'
        ELSE 'CONCLUIDA'
    END,
    0,
    SUBSTR(r.TXT_ERRO, 1, 2000),
    CAST(COALESCE(r.CTR_DTH_INC, SYSTIMESTAMP) AS DATE)
FROM CBM_ROTINA r
WHERE NOT EXISTS (SELECT 1 FROM SOL.ROTINA_EXECUCAO re WHERE re.ID_ROTINA_EXECUCAO = r.NRO_INT_ROTINA);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.ROTINA_EXECUCAO; DBMS_OUTPUT.PUT_LINE('ROTINA_EXECUCAO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 9 — Atualizar sequences SOL para evitar conflitos
-- ============================================================
PROMPT === PASSO 9: Atualizando sequences ===

DECLARE v NUMBER; BEGIN
  SELECT NVL(MAX(ID_USUARIO),0)        +1000 INTO v FROM SOL.USUARIO;        EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_USUARIO RESTART START WITH '        ||v; DBMS_OUTPUT.PUT_LINE('SEQ_USUARIO → '        ||v);
  SELECT NVL(MAX(ID_ENDERECO),0)       +1000 INTO v FROM SOL.ENDERECO;       EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_ENDERECO RESTART START WITH '       ||v; DBMS_OUTPUT.PUT_LINE('SEQ_ENDERECO → '       ||v);
  SELECT NVL(MAX(ID_LICENCIAMENTO),0)  +1000 INTO v FROM SOL.LICENCIAMENTO;  EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_LICENCIAMENTO RESTART START WITH '  ||v; DBMS_OUTPUT.PUT_LINE('SEQ_LICENCIAMENTO → '  ||v);
  SELECT NVL(MAX(ID_BOLETO),0)         +1000 INTO v FROM SOL.BOLETO;         EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_BOLETO RESTART START WITH '         ||v; DBMS_OUTPUT.PUT_LINE('SEQ_BOLETO → '         ||v);
  SELECT NVL(MAX(ID_MARCO_PROCESSO),0) +1000 INTO v FROM SOL.MARCO_PROCESSO; EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_MARCO_PROCESSO RESTART START WITH ' ||v; DBMS_OUTPUT.PUT_LINE('SEQ_MARCO_PROCESSO → ' ||v);
  SELECT NVL(MAX(ID_ARQUIVO_ED),0)     +1000 INTO v FROM SOL.ARQUIVO_ED;     EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_ARQUIVO_ED RESTART START WITH '     ||v; DBMS_OUTPUT.PUT_LINE('SEQ_ARQUIVO_ED → '     ||v);
  SELECT NVL(MAX(ID_ROTINA_EXECUCAO),0)+1000 INTO v FROM SOL.ROTINA_EXECUCAO;EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_ROTINA_EXECUCAO RESTART START WITH '||v; DBMS_OUTPUT.PUT_LINE('SEQ_ROTINA_EXECUCAO → '||v);
END;
/

-- ============================================================
-- PASSO 10 — Validação final
-- ============================================================
PROMPT === PASSO 10: Contagem final ===

SELECT 'SOL.USUARIO'         AS TABELA, COUNT(*) AS MIGRADOS FROM SOL.USUARIO         UNION ALL
SELECT 'SOL.ENDERECO',                  COUNT(*)             FROM SOL.ENDERECO         UNION ALL
SELECT 'SOL.LICENCIAMENTO',             COUNT(*)             FROM SOL.LICENCIAMENTO    UNION ALL
SELECT 'SOL.BOLETO',                    COUNT(*)             FROM SOL.BOLETO           UNION ALL
SELECT 'SOL.MARCO_PROCESSO',            COUNT(*)             FROM SOL.MARCO_PROCESSO   UNION ALL
SELECT 'SOL.ARQUIVO_ED',                COUNT(*)             FROM SOL.ARQUIVO_ED       UNION ALL
SELECT 'SOL.ROTINA_EXECUCAO',           COUNT(*)             FROM SOL.ROTINA_EXECUCAO;

PROMPT
PROMPT === Migração concluída sem erros. Descomente o COMMIT abaixo após validar. ===
PROMPT

-- COMMIT;

EXIT;
