-- ============================================================
-- migrar-licenciamento-patch.sql
-- Corrige o PASSO 4 do v3: ID_RESPONSAVEL_TECNICO e
-- ID_RESPONSAVEL_USO agora só são usados se o usuário existir
-- em SOL.USUARIO (evita ORA-02291 FK violation).
-- Execução:
--   sqlplus P_CBM_SOLCBM_AD/GuiGui1267@//localhost:1521/XEPDB1 "@C:\SOL\infra\scripts\migrar-licenciamento-patch.sql"
-- ============================================================
SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON

-- Diagnóstico: qual FK está falhando
SELECT c.constraint_name, c.r_constraint_name,
       cc.column_name, rc.table_name AS tabela_pai
FROM all_constraints c
JOIN all_cons_columns cc ON cc.constraint_name = c.constraint_name AND cc.owner = c.owner
JOIN all_constraints rc  ON rc.constraint_name = c.r_constraint_name
WHERE c.owner = 'SOL'
  AND c.table_name = 'LICENCIAMENTO'
  AND c.constraint_type = 'R'
ORDER BY c.constraint_name;

-- Quantos licenciamentos têm RT/RU cujo ID não está em SOL.USUARIO
DECLARE
  v_rt NUMBER; v_ru NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_rt
  FROM CBM_LICENCIAMENTO lic
  WHERE EXISTS (
    SELECT 1 FROM CBM_RESPONSAVEL_TECNICO rt
    WHERE rt.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
      AND rt.IND_ACEITE = 'S'
      AND NOT EXISTS (SELECT 1 FROM SOL.USUARIO u WHERE u.ID_USUARIO = rt.NRO_INT_USUARIO)
      AND ROWNUM = 1
  );
  SELECT COUNT(*) INTO v_ru
  FROM CBM_LICENCIAMENTO lic
  WHERE EXISTS (
    SELECT 1 FROM CBM_RESPONSAVEL_USO ru
    WHERE ru.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
      AND ru.IND_ACEITE = 'S'
      AND NOT EXISTS (SELECT 1 FROM SOL.USUARIO u WHERE u.ID_USUARIO = ru.NRO_INT_USUARIO)
      AND ROWNUM = 1
  );
  DBMS_OUTPUT.PUT_LINE('Licenciamentos com RT fora do SOL.USUARIO: ' || v_rt);
  DBMS_OUTPUT.PUT_LINE('Licenciamentos com RU fora do SOL.USUARIO: ' || v_ru);
END;
/

PROMPT === Migrando LICENCIAMENTO (com validação de FK para USUARIO) ===
INSERT INTO SOL.LICENCIAMENTO (
    ID_LICENCIAMENTO, NUMERO_PPCI, TIPO, STATUS,
    ID_ENDERECO, ID_RESPONSAVEL_TECNICO, ID_RESPONSAVEL_USO,
    ISENTO_TAXA, ISENTO_TAXA_RENOVACAO, ATIVO,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    lic.NRO_INT_LICENCIAMENTO,
    SUBSTR(lic.COD_LICENCIAMENTO, 1, 20),
    CASE WHEN UPPER(lic.TP_LICENCIAMENTO) LIKE '%PSPCIM%' THEN 'PSPCIM' ELSE 'PPCI' END,
    CASE lic.TP_SITUACAO
        WHEN 'RASCUNHO'                       THEN 'RASCUNHO'
        WHEN 'AGUARDANDO_DISTRIBUICAO'        THEN 'ANALISE_PENDENTE'
        WHEN 'AGUARDANDO_ENDERECO'            THEN 'ANALISE_PENDENTE'
        WHEN 'ANALISE_ENDERECO_PENDENTE'      THEN 'ANALISE_PENDENTE'
        WHEN 'AGUARDANDO_ACEITE'              THEN 'ANALISE_PENDENTE'
        WHEN 'EM_ANALISE'                     THEN 'EM_ANALISE'
        WHEN 'ANALISE_INVIABILIDADE_PENDENTE' THEN 'EM_ANALISE'
        WHEN 'AGUARDANDO_CIENCIA'             THEN 'CIA_EMITIDO'
        WHEN 'CA'                             THEN 'CIA_EMITIDO'
        WHEN 'AGUARDANDO_PAGAMENTO'           THEN 'CIA_CIENCIA'
        WHEN 'AGUARDANDO_PAGAMENTO_VISTORIA'  THEN 'CIA_CIENCIA'
        WHEN 'AGUARDANDO_PRPCI'               THEN 'CIV_EMITIDO'
        WHEN 'AGUARDANDO_ACEITE_PRPCI'        THEN 'PRPCI_EMITIDO'
        WHEN 'AGUARDA_DISTRIBUICAO_VISTORIA'  THEN 'VISTORIA_PENDENTE'
        WHEN 'AGUARDANDO_ACEITE_VISTORIA'     THEN 'VISTORIA_PENDENTE'
        WHEN 'EM_VISTORIA'                    THEN 'EM_VISTORIA'
        WHEN 'AGUARDANDO_CIENCIA_CIV'         THEN 'CIV_EMITIDO'
        WHEN 'CIV'                            THEN 'CIV_EMITIDO'
        WHEN 'NCA'                            THEN 'INDEFERIDO'
        WHEN 'ALVARA_VIGENTE'                 THEN 'APPCI_EMITIDO'
        WHEN 'ALVARA_VENCIDO'                 THEN 'ALVARA_VENCIDO'
        WHEN 'RECURSO_EM_ANALISE_1_CIA'       THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_2_CIA'       THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_1_CIV'       THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_2_CIV'       THEN 'EM_RECURSO'
        WHEN 'EXTINGUIDO'                     THEN 'EXTINTO'
        WHEN 'AGUARDANDO_ACEITES_EXTINCAO'    THEN 'EXTINTO'
        WHEN 'AGUARDANDO_ACEITE_RENOVACAO'    THEN 'AGUARDANDO_ACEITE_RENOVACAO'
        WHEN 'AGUARDANDO_PAGAMENTO_RENOVACAO' THEN 'AGUARDANDO_PAGAMENTO_RENOVACAO'
        WHEN 'AGUARDANDO_DISTRIBUICAO_RENOV'  THEN 'AGUARDANDO_DISTRIBUICAO_RENOV'
        WHEN 'EM_VISTORIA_RENOVACAO'          THEN 'EM_VISTORIA_RENOVACAO'
        ELSE 'ANALISE_PENDENTE'
    END,
    loc.NRO_INT_LOCALIZACAO,
    -- RT: NULL se o usuário não foi migrado
    (SELECT rt.NRO_INT_USUARIO
     FROM CBM_RESPONSAVEL_TECNICO rt
     WHERE rt.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
       AND rt.IND_ACEITE = 'S'
       AND EXISTS (SELECT 1 FROM SOL.USUARIO u WHERE u.ID_USUARIO = rt.NRO_INT_USUARIO)
       AND ROWNUM = 1),
    -- RU: NULL se o usuário não foi migrado
    (SELECT ru.NRO_INT_USUARIO
     FROM CBM_RESPONSAVEL_USO ru
     WHERE ru.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
       AND ru.IND_ACEITE = 'S'
       AND EXISTS (SELECT 1 FROM SOL.USUARIO u WHERE u.ID_USUARIO = ru.NRO_INT_USUARIO)
       AND ROWNUM = 1),
    CASE WHEN TRIM(lic.IND_ISENCAO) = 'S' THEN 'S' ELSE 'N' END,
    'N', 'S',
    CAST(COALESCE(lic.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(lic.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_LICENCIAMENTO lic
JOIN CBM_LOCALIZACAO loc ON loc.NRO_INT_LOCALIZACAO = lic.NRO_INT_LOCALIZACAO
WHERE lic.NRO_INT_LOCALIZACAO IS NOT NULL
  AND EXISTS (SELECT 1 FROM SOL.ENDERECO e WHERE e.ID_ENDERECO = loc.NRO_INT_LOCALIZACAO);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.LICENCIAMENTO; DBMS_OUTPUT.PUT_LINE('LICENCIAMENTO inserido: ' || v); END;
/

-- Continua com BOLETO, MARCO e ARQUIVO (idênticos ao v3)
PROMPT === Migrando BOLETO ===
INSERT INTO SOL.BOLETO (
    ID_BOLETO, NOSSO_NUMERO, CODIGO_BARRAS, LINHA_DIGITAVEL,
    VALOR, DT_EMISSAO, DT_VENCIMENTO, DT_PAGAMENTO,
    STATUS, ID_LICENCIAMENTO, DT_CRIACAO, DT_ATUALIZACAO
)
SELECT b.NRO_INT_BOLETO,
    SUBSTR(TO_CHAR(b.NRO_NOSSO_NUMERO), 1, 20),
    SUBSTR(b.TXT_CODIGO_BARRAS, 1, 60),
    SUBSTR(b.TXT_LINHA_DIGITAVEL, 1, 60),
    b.VALOR_NOMINAL, b.DATA_EMISSAO, b.DATA_VENCIMENTO, b.DATA_PAGAMENTO,
    CASE b.TP_SITUACAO WHEN 0 THEN 'CANCELADO' WHEN 1 THEN 'PENDENTE'
                       WHEN 2 THEN 'PAGO' ELSE 'PENDENTE' END,
    bl.NRO_INT_LICENCIAMENTO,
    CAST(COALESCE(b.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(b.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_BOLETO b
JOIN CBM_BOLETO_LICENCIAMENTO bl ON bl.NRO_INT_BOLETO = b.NRO_INT_BOLETO
WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = bl.NRO_INT_LICENCIAMENTO)
  AND b.VALOR_NOMINAL IS NOT NULL AND b.DATA_EMISSAO IS NOT NULL AND b.DATA_VENCIMENTO IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.BOLETO; DBMS_OUTPUT.PUT_LINE('BOLETO inserido: ' || v); END;
/

PROMPT === Migrando MARCO_PROCESSO ===
INSERT INTO SOL.MARCO_PROCESSO (
    ID_MARCO_PROCESSO, TIPO_MARCO, OBSERVACAO,
    ID_LICENCIAMENTO, ID_USUARIO, DT_MARCO
)
SELECT lm.NRO_INT_LIC_MARCO,
    CASE lm.NRO_INT_PARAMETRO_MARCO
        WHEN 1  THEN 'CIA_EMITIDO'           WHEN 2  THEN 'CIA_EMITIDO'
        WHEN 3  THEN 'REPROVACAO_ANALISE'    WHEN 4  THEN 'APROVACAO_ANALISE'
        WHEN 5  THEN 'CIA_CIENCIA'           WHEN 6  THEN 'CIA_CIENCIA'
        WHEN 7  THEN 'CIA_CIENCIA'           WHEN 8  THEN 'CIA_CIENCIA'
        WHEN 9  THEN 'DISTRIBUICAO'          WHEN 10 THEN 'ISENCAO_DEFERIDA'
        WHEN 11 THEN 'ISENCAO_INDEFERIDA'    WHEN 12 THEN 'DISTRIBUICAO'
        WHEN 13 THEN 'SUBMISSAO'             WHEN 14 THEN 'SUBMISSAO'
        WHEN 15 THEN 'DISTRIBUICAO'          WHEN 16 THEN 'EXTINCAO_EFETIVADA'
        WHEN 17 THEN 'SUBMISSAO'             WHEN 18 THEN 'CIA_CIENCIA'
        WHEN 19 THEN 'CIA_CIENCIA'           WHEN 20 THEN 'CIA_CIENCIA'
        WHEN 21 THEN 'CIA_CIENCIA'           WHEN 22 THEN 'ISENCAO_SOLICITADA'
        WHEN 23 THEN 'INICIO_ANALISE'        WHEN 24 THEN 'REPROVACAO_ANALISE'
        WHEN 25 THEN 'APROVACAO_ANALISE'     WHEN 26 THEN 'CIA_EMITIDO'
        WHEN 27 THEN 'CIV_EMITIDO'           WHEN 28 THEN 'APPCI_EMITIDO'
        WHEN 29 THEN 'CIV_CIENCIA'           WHEN 30 THEN 'DISTRIBUICAO'
        WHEN 31 THEN 'DISTRIBUICAO'          WHEN 32 THEN 'VISTORIA_AGENDADA'
        WHEN 33 THEN 'PAGAMENTO_CONFIRMADO'  WHEN 34 THEN 'PAGAMENTO_CONFIRMADO'
        WHEN 35 THEN 'CIV_CIENCIA'           WHEN 36 THEN 'BOLETO_GERADO'
        WHEN 37 THEN 'BOLETO_GERADO'         WHEN 38 THEN 'RASCUNHO_SALVO'
        WHEN 39 THEN 'VISTORIA_REPROVADA'    WHEN 40 THEN 'DISTRIBUICAO'
        WHEN 41 THEN 'APPCI_EMITIDO'         WHEN 42 THEN 'APPCI_EMITIDO'
        WHEN 43 THEN 'PRPCI_EMITIDO'         WHEN 44 THEN 'APPCI_EMITIDO'
        WHEN 45 THEN 'APPCI_EMITIDO'         WHEN 46 THEN 'SUBMISSAO'
        WHEN 47 THEN 'TROCA_RT_SOLICITADA'   WHEN 48 THEN 'TROCA_RT_AUTORIZADA'
        WHEN 49 THEN 'TROCA_RT_SOLICITADA'   WHEN 50 THEN 'TROCA_RT_EFETIVADA'
        WHEN 51 THEN 'VISTORIA_AGENDADA'     WHEN 52 THEN 'VISTORIA_AGENDADA'
        WHEN 61 THEN 'VISTORIA_AGENDADA'     WHEN 62 THEN 'ISENCAO_DEFERIDA'
        WHEN 63 THEN 'ISENCAO_INDEFERIDA'    WHEN 64 THEN 'DISTRIBUICAO'
        WHEN 65 THEN 'SUBMISSAO'             WHEN 66 THEN 'SUBMISSAO'
        WHEN 67 THEN 'PRPCI_EMITIDO'         WHEN 68 THEN 'PRPCI_EMITIDO'
        WHEN 69 THEN 'BOLETO_GERADO'         WHEN 70 THEN 'SUBMISSAO'
        WHEN 71 THEN 'CIA_CIENCIA'           WHEN 72 THEN 'DISTRIBUICAO'
        WHEN 73 THEN 'SUBMISSAO'             WHEN 74 THEN 'APROVACAO_ANALISE'
        WHEN 75 THEN 'PAGAMENTO_CONFIRMADO'  WHEN 76 THEN 'SUBMISSAO'
        WHEN 77 THEN 'SUBMISSAO'             WHEN 78 THEN 'ISENCAO_SOLICITADA'
        WHEN 79 THEN 'CIA_EMITIDO'           WHEN 80 THEN 'CIA_CIENCIA'
        WHEN 81 THEN 'RECURSO_EM_ANALISE'    WHEN 82 THEN 'RECURSO_EM_ANALISE'
        WHEN 83 THEN 'RECURSO_INTERPOSTO'    WHEN 84 THEN 'CIENCIA_RECURSO'
        WHEN 85 THEN 'RECURSO_EM_ANALISE'    WHEN 86 THEN 'RECURSO_EM_ANALISE'
        WHEN 87 THEN 'RECURSO_EM_ANALISE'    WHEN 88 THEN 'CIA_EMITIDO'
        WHEN 89 THEN 'RECURSO_EM_ANALISE'    WHEN 90 THEN 'RECURSO_EM_ANALISE'
        WHEN 91 THEN 'RECURSO_INDEFERIDO'    WHEN 92 THEN 'RECURSO_INDEFERIDO'
        WHEN 93 THEN 'RECURSO_EM_ANALISE'    WHEN 94 THEN 'RECURSO_EM_ANALISE'
        WHEN 95 THEN 'RECURSO_EM_ANALISE'    WHEN 101 THEN 'VISTORIA_AGENDADA'
        WHEN 121 THEN 'RASCUNHO_SALVO'       WHEN 141 THEN 'ACEITE_ANEXOD_RENOVACAO'
        WHEN 142 THEN 'RECURSO_INDEFERIDO'   WHEN 143 THEN 'NOTIFICACAO_ALVARA_VENCIDO'
        WHEN 144 THEN 'ENVIO_VISTORIA_RENOVACAO'
        WHEN 145 THEN 'LIQUIDACAO_VISTORIA_RENOVACAO'
        WHEN 146 THEN 'BOLETO_VISTORIA_RENOVACAO_PPCI'
        WHEN 147 THEN 'ACEITE_VISTORIA_RENOVACAO'
        WHEN 148 THEN 'FIM_ACEITES_VISTORIA_RENOVACAO'
        WHEN 149 THEN 'DISTRIBUICAO_VISTORIA_RENOV'
        WHEN 150 THEN 'ANALISE_ISENCAO_RENOV_APROVADO'
        WHEN 151 THEN 'ANALISE_ISENCAO_RENOV_REPROVADO'
        WHEN 152 THEN 'NOTIFICACAO_SOLICITAR_RENOVACAO_90'
        WHEN 153 THEN 'NOTIFICACAO_SOLIC_RENOV_PRAZO_VENCIDO_59'
        WHEN 154 THEN 'NOTIFICACAO_SOLIC_RENOV_PRAZO_VENCIDO_29'
        WHEN 155 THEN 'NOTIFICACAO_ALVARA_VENCIDO'
        WHEN 156 THEN 'VISTORIA_RENOVACAO_CIV'    WHEN 157 THEN 'VISTORIA_RENOVACAO'
        WHEN 158 THEN 'HOMOLOG_VISTORIA_RENOV_INDEFERIDO'
        WHEN 159 THEN 'HOMOLOG_VISTORIA_RENOV_DEFERIDO'
        WHEN 160 THEN 'EMISSAO_DOC_COMPLEMENTAR_RENOV'
        WHEN 161 THEN 'CIENCIA_APPCI_RENOVACAO'   WHEN 162 THEN 'PRPCI_EMITIDO'
        WHEN 163 THEN 'LIBERACAO_RENOV_APPCI'
        WHEN 164 THEN 'SOLICITACAO_ISENCAO_RENOVACAO'
        WHEN 165 THEN 'CIENCIA_CIV_RENOVACAO'
        WHEN 181 THEN 'APPCI_EMITIDO'   WHEN 182 THEN 'VISTORIA_REALIZADA'
        WHEN 183 THEN 'VISTORIA_REALIZADA' WHEN 184 THEN 'VISTORIA_REALIZADA'
        WHEN 201 THEN 'RECURSO_INDEFERIDO' WHEN 202 THEN 'RECURSO_INTERPOSTO'
        WHEN 203 THEN 'RECURSO_INDEFERIDO' WHEN 221 THEN 'EXTINCAO_SOLICITADA'
        WHEN 222 THEN 'EXTINCAO_SOLICITADA' WHEN 223 THEN 'EXTINCAO_SOLICITADA'
        WHEN 224 THEN 'EXTINCAO_SOLICITADA' WHEN 241 THEN 'VISTORIA_AGENDADA'
        WHEN 261 THEN 'SUBMISSAO'           WHEN 262 THEN 'SUBMISSAO'
        ELSE 'SUBMISSAO'
    END,
    SUBSTR(lm.TXT_DESCRICAO || CASE WHEN lm.TXT_COMPLEMENTAR IS NOT NULL
           THEN ' | ' || lm.TXT_COMPLEMENTAR ELSE '' END, 1, 4000),
    lm.NRO_INT_LICENCIAMENTO,
    CASE WHEN EXISTS (SELECT 1 FROM SOL.USUARIO u WHERE u.ID_USUARIO = lm.NRO_INT_USUARIO_RESP)
         THEN lm.NRO_INT_USUARIO_RESP ELSE NULL END,
    CAST(lm.DTH_MARCO AS DATE)
FROM CBM_LICENCIAMENTO_MARCO lm
WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = lm.NRO_INT_LICENCIAMENTO)
  AND lm.TXT_DESCRICAO IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.MARCO_PROCESSO; DBMS_OUTPUT.PUT_LINE('MARCO_PROCESSO inserido: ' || v); END;
/

PROMPT === Migrando ARQUIVO_ED ===
INSERT INTO SOL.ARQUIVO_ED (
    ID_ARQUIVO_ED, NOME_ARQUIVO, IDENTIFICADOR_ALFRESCO,
    TIPO_ARQUIVO, ID_LICENCIAMENTO, DT_UPLOAD
)
SELECT NRO_INT_ARQUIVO, NOME_ARQUIVO, IDENT_ALFRESCO, TIPO, ID_LIC, DT_UP
FROM (
    SELECT a.NRO_INT_ARQUIVO,
           SUBSTR(COALESCE(a.NOME_ARQUIVO,'sem-nome'),1,500) AS NOME_ARQUIVO,
           SUBSTR(a.TXT_IDENTIFICADOR_ALFRESCO,1,500) AS IDENT_ALFRESCO,
           'PRPCI' AS TIPO, p.NRO_INT_LICENCIAMENTO AS ID_LIC,
           CAST(COALESCE(a.CTR_DTH_INC,SYSTIMESTAMP) AS DATE) AS DT_UP
    FROM CBM_PRPCI p JOIN CBM_ARQUIVO a ON a.NRO_INT_ARQUIVO = p.NRO_INT_ARQUIVO
    WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = p.NRO_INT_LICENCIAMENTO)
    UNION ALL
    SELECT a.NRO_INT_ARQUIVO,
           SUBSTR(COALESCE(a.NOME_ARQUIVO,'sem-nome'),1,500),
           SUBSTR(a.TXT_IDENTIFICADOR_ALFRESCO,1,500),
           'APPCI', ap.NRO_INT_LICENCIAMENTO,
           CAST(COALESCE(a.CTR_DTH_INC,SYSTIMESTAMP) AS DATE)
    FROM CBM_APPCI ap JOIN CBM_ARQUIVO a ON a.NRO_INT_ARQUIVO = ap.NRO_INT_ARQUIVO
    WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = ap.NRO_INT_LICENCIAMENTO)
) src
WHERE NOT EXISTS (SELECT 1 FROM SOL.ARQUIVO_ED ae WHERE ae.ID_ARQUIVO_ED = src.NRO_INT_ARQUIVO);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.ARQUIVO_ED; DBMS_OUTPUT.PUT_LINE('ARQUIVO_ED inserido: ' || v); END;
/

PROMPT === Atualizando sequences ===
DECLARE v NUMBER; BEGIN
  SELECT NVL(MAX(ID_LICENCIAMENTO),0) +1000 INTO v FROM SOL.LICENCIAMENTO; EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_LICENCIAMENTO RESTART START WITH ' ||v; DBMS_OUTPUT.PUT_LINE('SEQ_LICENCIAMENTO → '||v);
  SELECT NVL(MAX(ID_BOLETO),0)        +1000 INTO v FROM SOL.BOLETO;        EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_BOLETO RESTART START WITH '        ||v; DBMS_OUTPUT.PUT_LINE('SEQ_BOLETO → '        ||v);
  SELECT NVL(MAX(ID_MARCO_PROCESSO),0)+1000 INTO v FROM SOL.MARCO_PROCESSO;EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_MARCO_PROCESSO RESTART START WITH '||v; DBMS_OUTPUT.PUT_LINE('SEQ_MARCO_PROCESSO → '||v);
  SELECT NVL(MAX(ID_ARQUIVO_ED),0)    +1000 INTO v FROM SOL.ARQUIVO_ED;    EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_ARQUIVO_ED RESTART START WITH '    ||v; DBMS_OUTPUT.PUT_LINE('SEQ_ARQUIVO_ED → '    ||v);
END;
/

PROMPT === Contagem final ===
SELECT 'SOL.USUARIO'         AS TABELA, COUNT(*) AS MIGRADOS FROM SOL.USUARIO         UNION ALL
SELECT 'SOL.ENDERECO',                  COUNT(*)             FROM SOL.ENDERECO         UNION ALL
SELECT 'SOL.LICENCIAMENTO',             COUNT(*)             FROM SOL.LICENCIAMENTO    UNION ALL
SELECT 'SOL.BOLETO',                    COUNT(*)             FROM SOL.BOLETO           UNION ALL
SELECT 'SOL.MARCO_PROCESSO',            COUNT(*)             FROM SOL.MARCO_PROCESSO   UNION ALL
SELECT 'SOL.ARQUIVO_ED',                COUNT(*)             FROM SOL.ARQUIVO_ED       UNION ALL
SELECT 'SOL.ROTINA_EXECUCAO',           COUNT(*)             FROM SOL.ROTINA_EXECUCAO;

PROMPT
PROMPT === Sem erros? Descomente o COMMIT abaixo. ===
-- COMMIT;
EXIT;
