-- ============================================================
-- migrar-producao-v3.sql  —  SOL CBM-RS  (versão final)
-- Execução:
--   sqlplus P_CBM_SOLCBM_AD/GuiGui1267@//localhost:1521/XEPDB1 @migrar-producao-v3.sql
-- ============================================================
SET SERVEROUTPUT ON SIZE UNLIMITED
SET PAGESIZE 0
SET FEEDBACK ON

-- ============================================================
-- PASSO 1 — Limpar schema SOL (ordem inversa das FKs)
-- ============================================================
PROMPT === PASSO 1: Limpando schema SOL ===
DELETE FROM SOL.ARQUIVO_ED;
DELETE FROM SOL.MARCO_PROCESSO;
DELETE FROM SOL.BOLETO;
DELETE FROM SOL.LICENCIAMENTO;
DELETE FROM SOL.ENDERECO;
DELETE FROM SOL.USUARIO;
DELETE FROM SOL.ROTINA_EXECUCAO;
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM SOL.USUARIO;        DBMS_OUTPUT.PUT_LINE('USUARIO: '        || v);
  SELECT COUNT(*) INTO v FROM SOL.LICENCIAMENTO;  DBMS_OUTPUT.PUT_LINE('LICENCIAMENTO: '  || v);
END;
/

-- ============================================================
-- PASSO 2 — USUARIO
--   Deduplicação por email: mantém o registro mais antigo
--   StatusCadastro: 0=INCOMPLETO 1=ANALISE_PENDENTE 2=EM_ANALISE
--                   3=APROVADO   4=REPROVADO
-- ============================================================
PROMPT === PASSO 2: Migrando USUARIO ===
INSERT INTO SOL.USUARIO (
    ID_USUARIO, CPF, NOME, EMAIL, TELEFONE,
    TIPO_USUARIO, STATUS_CADASTRO, ATIVO,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT NRO_INT_USUARIO, CPF, NOME, EMAIL, TELEFONE,
       TIPO_USUARIO, STATUS_CADASTRO, ATIVO,
       DT_CRIACAO, DT_ATUALIZACAO
FROM (
    SELECT
        u.NRO_INT_USUARIO,
        SUBSTR(REGEXP_REPLACE(u.TXT_CPF, '[^0-9]', ''), 1, 11)   AS CPF,
        SUBSTR(u.NOME_USUARIO, 1, 200)                            AS NOME,
        LOWER(TRIM(u.TXT_EMAIL))                                  AS EMAIL,
        SUBSTR(u.TXT_TELEFONE1, 1, 20)                            AS TELEFONE,
        CASE
            WHEN EXISTS (SELECT 1 FROM CBM_RESPONSAVEL_TECNICO rt
                         WHERE rt.NRO_INT_USUARIO = u.NRO_INT_USUARIO AND ROWNUM = 1)
            THEN 'RT' ELSE 'CIDADAO'
        END                                                       AS TIPO_USUARIO,
        CASE u.TP_STATUS
            WHEN 0 THEN 'INCOMPLETO'
            WHEN 1 THEN 'ANALISE_PENDENTE'
            WHEN 2 THEN 'EM_ANALISE'
            WHEN 3 THEN 'APROVADO'
            WHEN 4 THEN 'REPROVADO'
            ELSE        'INCOMPLETO'
        END                                                       AS STATUS_CADASTRO,
        'S'                                                       AS ATIVO,
        CAST(COALESCE(u.CTR_DTH_INC, SYSTIMESTAMP) AS DATE)      AS DT_CRIACAO,
        CAST(COALESCE(u.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)      AS DT_ATUALIZACAO,
        ROW_NUMBER() OVER (
            PARTITION BY LOWER(TRIM(u.TXT_EMAIL))
            ORDER BY u.NRO_INT_USUARIO ASC
        ) AS RN
    FROM CBM_USUARIO u
    WHERE u.TXT_EMAIL IS NOT NULL
      AND TRIM(u.TXT_EMAIL) IS NOT NULL
      AND REGEXP_REPLACE(u.TXT_CPF, '[^0-9]', '') IS NOT NULL
)
WHERE RN = 1;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.USUARIO; DBMS_OUTPUT.PUT_LINE('USUARIO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 3 — ENDERECO (CEP NULL → '00000000' como placeholder)
-- ============================================================
PROMPT === PASSO 3: Migrando ENDERECO ===
INSERT INTO SOL.ENDERECO (
    ID_ENDERECO, CEP, LOGRADOURO, NUMERO, COMPLEMENTO,
    BAIRRO, MUNICIPIO, UF, LATITUDE, LONGITUDE,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    loc.NRO_INT_LOCALIZACAO,
    COALESCE(SUBSTR(REGEXP_REPLACE(loc.TXT_CEP, '[^0-9]', ''), 1, 8), '00000000'),
    SUBSTR(el.TXT_LOGRADOURO, 1, 200),
    SUBSTR(TO_CHAR(el.NRO_IMOVEL), 1, 20),
    SUBSTR(loc.TXT_COMPLEMENTO, 1, 100),
    SUBSTR(COALESCE(loc.TXT_BAIRRO, 'NAO INFORMADO'), 1, 100),
    SUBSTR(el.TXT_CIDADE, 1, 100),
    SUBSTR(el.SIGLA_UF, 1, 2),
    loc.NRO_LATITUDE_MAPA,
    loc.NRO_LONGITUDE_MAPA,
    CAST(COALESCE(loc.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(loc.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_LICENCIAMENTO lic
JOIN CBM_LOCALIZACAO loc
    ON loc.NRO_INT_LOCALIZACAO = lic.NRO_INT_LOCALIZACAO
JOIN CBM_ENDERECO_LICENCIAMENTO el
    ON el.NRO_INT_ENDERECO_LICENCIAMENTO = loc.NRO_INT_ENDERECO_LICENCIAMENTO
WHERE lic.NRO_INT_LOCALIZACAO IS NOT NULL
  AND el.TXT_LOGRADOURO IS NOT NULL
  AND el.TXT_CIDADE IS NOT NULL
  AND el.SIGLA_UF IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.ENDERECO; DBMS_OUTPUT.PUT_LINE('ENDERECO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 4 — LICENCIAMENTO
--   Mapeamento completo de TP_SITUACAO para StatusLicenciamento
-- ============================================================
PROMPT === PASSO 4: Migrando LICENCIAMENTO ===
INSERT INTO SOL.LICENCIAMENTO (
    ID_LICENCIAMENTO, NUMERO_PPCI, TIPO, STATUS,
    ID_ENDERECO, ID_RESPONSAVEL_TECNICO, ID_RESPONSAVEL_USO,
    ISENTO_TAXA, ISENTO_TAXA_RENOVACAO, ATIVO,
    DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    lic.NRO_INT_LICENCIAMENTO,
    SUBSTR(lic.COD_LICENCIAMENTO, 1, 20),
    CASE WHEN UPPER(lic.TP_LICENCIAMENTO) LIKE '%PSPCIM%' THEN 'PSPCIM' ELSE 'PPCI' END,
    CASE lic.TP_SITUACAO
        WHEN 'RASCUNHO'                      THEN 'RASCUNHO'
        WHEN 'AGUARDANDO_DISTRIBUICAO'       THEN 'ANALISE_PENDENTE'
        WHEN 'AGUARDANDO_ENDERECO'           THEN 'ANALISE_PENDENTE'
        WHEN 'ANALISE_ENDERECO_PENDENTE'     THEN 'ANALISE_PENDENTE'
        WHEN 'AGUARDANDO_ACEITE'             THEN 'ANALISE_PENDENTE'
        WHEN 'EM_ANALISE'                    THEN 'EM_ANALISE'
        WHEN 'ANALISE_INVIABILIDADE_PENDENTE' THEN 'EM_ANALISE'
        WHEN 'AGUARDANDO_CIENCIA'            THEN 'CIA_EMITIDO'
        WHEN 'CA'                            THEN 'CIA_EMITIDO'
        WHEN 'AGUARDANDO_PAGAMENTO'          THEN 'CIA_CIENCIA'
        WHEN 'AGUARDANDO_PAGAMENTO_VISTORIA' THEN 'CIA_CIENCIA'
        WHEN 'AGUARDANDO_PRPCI'              THEN 'CIV_EMITIDO'
        WHEN 'AGUARDANDO_ACEITE_PRPCI'       THEN 'PRPCI_EMITIDO'
        WHEN 'AGUARDA_DISTRIBUICAO_VISTORIA' THEN 'VISTORIA_PENDENTE'
        WHEN 'AGUARDANDO_ACEITE_VISTORIA'    THEN 'VISTORIA_PENDENTE'
        WHEN 'EM_VISTORIA'                   THEN 'EM_VISTORIA'
        WHEN 'AGUARDANDO_CIENCIA_CIV'        THEN 'CIV_EMITIDO'
        WHEN 'CIV'                           THEN 'CIV_EMITIDO'
        WHEN 'NCA'                           THEN 'INDEFERIDO'
        WHEN 'ALVARA_VIGENTE'                THEN 'APPCI_EMITIDO'
        WHEN 'ALVARA_VENCIDO'                THEN 'ALVARA_VENCIDO'
        WHEN 'RECURSO_EM_ANALISE_1_CIA'      THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_2_CIA'      THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_1_CIV'      THEN 'EM_RECURSO'
        WHEN 'RECURSO_EM_ANALISE_2_CIV'      THEN 'EM_RECURSO'
        WHEN 'EXTINGUIDO'                    THEN 'EXTINTO'
        WHEN 'AGUARDANDO_ACEITES_EXTINCAO'   THEN 'EXTINTO'
        WHEN 'AGUARDANDO_ACEITE_RENOVACAO'   THEN 'AGUARDANDO_ACEITE_RENOVACAO'
        WHEN 'AGUARDANDO_PAGAMENTO_RENOVACAO' THEN 'AGUARDANDO_PAGAMENTO_RENOVACAO'
        WHEN 'AGUARDANDO_DISTRIBUICAO_RENOV' THEN 'AGUARDANDO_DISTRIBUICAO_RENOV'
        WHEN 'EM_VISTORIA_RENOVACAO'         THEN 'EM_VISTORIA_RENOVACAO'
        ELSE 'ANALISE_PENDENTE'
    END,
    loc.NRO_INT_LOCALIZACAO,
    (SELECT rt.NRO_INT_USUARIO FROM CBM_RESPONSAVEL_TECNICO rt
     WHERE rt.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
       AND rt.IND_ACEITE = 'S' AND ROWNUM = 1),
    (SELECT ru.NRO_INT_USUARIO FROM CBM_RESPONSAVEL_USO ru
     WHERE ru.NRO_INT_LICENCIAMENTO = lic.NRO_INT_LICENCIAMENTO
       AND ru.IND_ACEITE = 'S' AND ROWNUM = 1),
    CASE WHEN TRIM(lic.IND_ISENCAO) = 'S' THEN 'S' ELSE 'N' END,
    'N',
    'S',
    CAST(COALESCE(lic.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(lic.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_LICENCIAMENTO lic
JOIN CBM_LOCALIZACAO loc ON loc.NRO_INT_LOCALIZACAO = lic.NRO_INT_LOCALIZACAO
WHERE lic.NRO_INT_LOCALIZACAO IS NOT NULL
  AND EXISTS (SELECT 1 FROM SOL.ENDERECO e WHERE e.ID_ENDERECO = loc.NRO_INT_LOCALIZACAO);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.LICENCIAMENTO; DBMS_OUTPUT.PUT_LINE('LICENCIAMENTO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 5 — BOLETO  (TP_SITUACAO: 0=CANCELADO 1=PENDENTE 2=PAGO)
-- ============================================================
PROMPT === PASSO 5: Migrando BOLETO ===
INSERT INTO SOL.BOLETO (
    ID_BOLETO, NOSSO_NUMERO, CODIGO_BARRAS, LINHA_DIGITAVEL,
    VALOR, DT_EMISSAO, DT_VENCIMENTO, DT_PAGAMENTO,
    STATUS, ID_LICENCIAMENTO, DT_CRIACAO, DT_ATUALIZACAO
)
SELECT
    b.NRO_INT_BOLETO,
    SUBSTR(TO_CHAR(b.NRO_NOSSO_NUMERO), 1, 20),
    SUBSTR(b.TXT_CODIGO_BARRAS, 1, 60),
    SUBSTR(b.TXT_LINHA_DIGITAVEL, 1, 60),
    b.VALOR_NOMINAL,
    b.DATA_EMISSAO,
    b.DATA_VENCIMENTO,
    b.DATA_PAGAMENTO,
    CASE b.TP_SITUACAO WHEN 0 THEN 'CANCELADO' WHEN 1 THEN 'PENDENTE'
                       WHEN 2 THEN 'PAGO' ELSE 'PENDENTE' END,
    bl.NRO_INT_LICENCIAMENTO,
    CAST(COALESCE(b.CTR_DTH_INC, SYSTIMESTAMP) AS DATE),
    CAST(COALESCE(b.CTR_DTH_ATU, SYSTIMESTAMP) AS DATE)
FROM CBM_BOLETO b
JOIN CBM_BOLETO_LICENCIAMENTO bl ON bl.NRO_INT_BOLETO = b.NRO_INT_BOLETO
WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = bl.NRO_INT_LICENCIAMENTO)
  AND b.VALOR_NOMINAL IS NOT NULL
  AND b.DATA_EMISSAO IS NOT NULL
  AND b.DATA_VENCIMENTO IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.BOLETO; DBMS_OUTPUT.PUT_LINE('BOLETO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 6 — MARCO_PROCESSO
--   Mapeamento por NRO_INT_PARAMETRO_MARCO (TXT_CHAVE)
-- ============================================================
PROMPT === PASSO 6: Migrando MARCO_PROCESSO ===
INSERT INTO SOL.MARCO_PROCESSO (
    ID_MARCO_PROCESSO, TIPO_MARCO, OBSERVACAO,
    ID_LICENCIAMENTO, ID_USUARIO, DT_MARCO
)
SELECT
    lm.NRO_INT_LIC_MARCO,
    CASE lm.NRO_INT_PARAMETRO_MARCO
        WHEN 1  THEN 'CIA_EMITIDO'
        WHEN 2  THEN 'CIA_EMITIDO'
        WHEN 3  THEN 'REPROVACAO_ANALISE'
        WHEN 4  THEN 'APROVACAO_ANALISE'
        WHEN 5  THEN 'CIA_CIENCIA'
        WHEN 6  THEN 'CIA_CIENCIA'
        WHEN 7  THEN 'CIA_CIENCIA'
        WHEN 8  THEN 'CIA_CIENCIA'
        WHEN 9  THEN 'DISTRIBUICAO'
        WHEN 10 THEN 'ISENCAO_DEFERIDA'
        WHEN 11 THEN 'ISENCAO_INDEFERIDA'
        WHEN 12 THEN 'DISTRIBUICAO'
        WHEN 13 THEN 'SUBMISSAO'
        WHEN 14 THEN 'SUBMISSAO'
        WHEN 15 THEN 'DISTRIBUICAO'
        WHEN 16 THEN 'EXTINCAO_EFETIVADA'
        WHEN 17 THEN 'SUBMISSAO'
        WHEN 18 THEN 'CIA_CIENCIA'
        WHEN 19 THEN 'CIA_CIENCIA'
        WHEN 20 THEN 'CIA_CIENCIA'
        WHEN 21 THEN 'CIA_CIENCIA'
        WHEN 22 THEN 'ISENCAO_SOLICITADA'
        WHEN 23 THEN 'INICIO_ANALISE'
        WHEN 24 THEN 'REPROVACAO_ANALISE'
        WHEN 25 THEN 'APROVACAO_ANALISE'
        WHEN 26 THEN 'CIA_EMITIDO'
        WHEN 27 THEN 'CIV_EMITIDO'
        WHEN 28 THEN 'APPCI_EMITIDO'
        WHEN 29 THEN 'CIV_CIENCIA'
        WHEN 30 THEN 'DISTRIBUICAO'
        WHEN 31 THEN 'DISTRIBUICAO'
        WHEN 32 THEN 'VISTORIA_AGENDADA'
        WHEN 33 THEN 'PAGAMENTO_CONFIRMADO'
        WHEN 34 THEN 'PAGAMENTO_CONFIRMADO'
        WHEN 35 THEN 'CIV_CIENCIA'
        WHEN 36 THEN 'BOLETO_GERADO'
        WHEN 37 THEN 'BOLETO_GERADO'
        WHEN 38 THEN 'RASCUNHO_SALVO'
        WHEN 39 THEN 'VISTORIA_REPROVADA'
        WHEN 40 THEN 'DISTRIBUICAO'
        WHEN 41 THEN 'APPCI_EMITIDO'
        WHEN 42 THEN 'APPCI_EMITIDO'
        WHEN 43 THEN 'PRPCI_EMITIDO'
        WHEN 44 THEN 'APPCI_EMITIDO'
        WHEN 45 THEN 'APPCI_EMITIDO'
        WHEN 46 THEN 'SUBMISSAO'
        WHEN 47 THEN 'TROCA_RT_SOLICITADA'
        WHEN 48 THEN 'TROCA_RT_AUTORIZADA'
        WHEN 49 THEN 'TROCA_RT_SOLICITADA'
        WHEN 50 THEN 'TROCA_RT_EFETIVADA'
        WHEN 51 THEN 'VISTORIA_AGENDADA'
        WHEN 52 THEN 'VISTORIA_AGENDADA'
        WHEN 61 THEN 'VISTORIA_AGENDADA'
        WHEN 62 THEN 'ISENCAO_DEFERIDA'
        WHEN 63 THEN 'ISENCAO_INDEFERIDA'
        WHEN 64 THEN 'DISTRIBUICAO'
        WHEN 65 THEN 'SUBMISSAO'
        WHEN 66 THEN 'SUBMISSAO'
        WHEN 67 THEN 'PRPCI_EMITIDO'
        WHEN 68 THEN 'PRPCI_EMITIDO'
        WHEN 69 THEN 'BOLETO_GERADO'
        WHEN 70 THEN 'SUBMISSAO'
        WHEN 71 THEN 'CIA_CIENCIA'
        WHEN 72 THEN 'DISTRIBUICAO'
        WHEN 73 THEN 'SUBMISSAO'
        WHEN 74 THEN 'APROVACAO_ANALISE'
        WHEN 75 THEN 'PAGAMENTO_CONFIRMADO'
        WHEN 76 THEN 'SUBMISSAO'
        WHEN 77 THEN 'SUBMISSAO'
        WHEN 78 THEN 'ISENCAO_SOLICITADA'
        WHEN 79 THEN 'CIA_EMITIDO'
        WHEN 80 THEN 'CIA_CIENCIA'
        WHEN 81 THEN 'RECURSO_EM_ANALISE'
        WHEN 82 THEN 'RECURSO_EM_ANALISE'
        WHEN 83 THEN 'RECURSO_INTERPOSTO'
        WHEN 84 THEN 'CIENCIA_RECURSO'
        WHEN 85 THEN 'RECURSO_EM_ANALISE'
        WHEN 86 THEN 'RECURSO_EM_ANALISE'
        WHEN 87 THEN 'RECURSO_EM_ANALISE'
        WHEN 88 THEN 'CIA_EMITIDO'
        WHEN 89 THEN 'RECURSO_EM_ANALISE'
        WHEN 90 THEN 'RECURSO_EM_ANALISE'
        WHEN 91 THEN 'RECURSO_INDEFERIDO'
        WHEN 92 THEN 'RECURSO_INDEFERIDO'
        WHEN 93 THEN 'RECURSO_EM_ANALISE'
        WHEN 94 THEN 'RECURSO_EM_ANALISE'
        WHEN 95 THEN 'RECURSO_EM_ANALISE'
        WHEN 101 THEN 'VISTORIA_AGENDADA'
        WHEN 121 THEN 'RASCUNHO_SALVO'
        WHEN 141 THEN 'ACEITE_ANEXOD_RENOVACAO'
        WHEN 142 THEN 'RECURSO_INDEFERIDO'
        WHEN 143 THEN 'NOTIFICACAO_ALVARA_VENCIDO'
        WHEN 144 THEN 'ENVIO_VISTORIA_RENOVACAO'
        WHEN 145 THEN 'LIQUIDACAO_VISTORIA_RENOVACAO'
        WHEN 146 THEN 'BOLETO_VISTORIA_RENOVACAO_PPCI'
        WHEN 147 THEN 'ACEITE_VISTORIA_RENOVACAO'
        WHEN 148 THEN 'FIM_ACEITES_VISTORIA_RENOVACAO'
        WHEN 149 THEN 'DISTRIBUICAO_VISTORIA_RENOV'
        WHEN 150 THEN 'ANALISE_ISENCAO_RENOV_APROVADO'
        WHEN 151 THEN 'ANALISE_ISENCAO_RENOV_REPROVADO'
        WHEN 152 THEN 'NOTIFICACAO_SOLICITAR_RENOVACAO_90'
        WHEN 153 THEN 'NOTIFICACAO_SOLIC_RENOV_PRAZO_VENCIDO_59'
        WHEN 154 THEN 'NOTIFICACAO_SOLIC_RENOV_PRAZO_VENCIDO_29'
        WHEN 155 THEN 'NOTIFICACAO_ALVARA_VENCIDO'
        WHEN 156 THEN 'VISTORIA_RENOVACAO_CIV'
        WHEN 157 THEN 'VISTORIA_RENOVACAO'
        WHEN 158 THEN 'HOMOLOG_VISTORIA_RENOV_INDEFERIDO'
        WHEN 159 THEN 'HOMOLOG_VISTORIA_RENOV_DEFERIDO'
        WHEN 160 THEN 'EMISSAO_DOC_COMPLEMENTAR_RENOV'
        WHEN 161 THEN 'CIENCIA_APPCI_RENOVACAO'
        WHEN 162 THEN 'PRPCI_EMITIDO'
        WHEN 163 THEN 'LIBERACAO_RENOV_APPCI'
        WHEN 164 THEN 'SOLICITACAO_ISENCAO_RENOVACAO'
        WHEN 165 THEN 'CIENCIA_CIV_RENOVACAO'
        WHEN 181 THEN 'APPCI_EMITIDO'
        WHEN 182 THEN 'VISTORIA_REALIZADA'
        WHEN 183 THEN 'VISTORIA_REALIZADA'
        WHEN 184 THEN 'VISTORIA_REALIZADA'
        WHEN 201 THEN 'RECURSO_INDEFERIDO'
        WHEN 202 THEN 'RECURSO_INTERPOSTO'
        WHEN 203 THEN 'RECURSO_INDEFERIDO'
        WHEN 221 THEN 'EXTINCAO_SOLICITADA'
        WHEN 222 THEN 'EXTINCAO_SOLICITADA'
        WHEN 223 THEN 'EXTINCAO_SOLICITADA'
        WHEN 224 THEN 'EXTINCAO_SOLICITADA'
        WHEN 241 THEN 'VISTORIA_AGENDADA'
        WHEN 261 THEN 'SUBMISSAO'
        WHEN 262 THEN 'SUBMISSAO'
        ELSE         'SUBMISSAO'
    END,
    SUBSTR(lm.TXT_DESCRICAO ||
           CASE WHEN lm.TXT_COMPLEMENTAR IS NOT NULL
                THEN ' | ' || lm.TXT_COMPLEMENTAR ELSE '' END, 1, 4000),
    lm.NRO_INT_LICENCIAMENTO,
    lm.NRO_INT_USUARIO_RESP,
    CAST(lm.DTH_MARCO AS DATE)
FROM CBM_LICENCIAMENTO_MARCO lm
WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = lm.NRO_INT_LICENCIAMENTO)
  AND lm.TXT_DESCRICAO IS NOT NULL;

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.MARCO_PROCESSO; DBMS_OUTPUT.PUT_LINE('MARCO_PROCESSO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 7 — ARQUIVO_ED (PRPCI + APPCI)
-- ============================================================
PROMPT === PASSO 7: Migrando ARQUIVO_ED ===
INSERT INTO SOL.ARQUIVO_ED (
    ID_ARQUIVO_ED, NOME_ARQUIVO, IDENTIFICADOR_ALFRESCO,
    TIPO_ARQUIVO, ID_LICENCIAMENTO, DT_UPLOAD
)
SELECT NRO_INT_ARQUIVO, NOME_ARQUIVO, IDENT_ALFRESCO, TIPO, ID_LIC, DT_UP
FROM (
    SELECT a.NRO_INT_ARQUIVO,
           SUBSTR(COALESCE(a.NOME_ARQUIVO, 'sem-nome'), 1, 500) AS NOME_ARQUIVO,
           SUBSTR(a.TXT_IDENTIFICADOR_ALFRESCO, 1, 500) AS IDENT_ALFRESCO,
           'PRPCI' AS TIPO,
           p.NRO_INT_LICENCIAMENTO AS ID_LIC,
           CAST(COALESCE(a.CTR_DTH_INC, SYSTIMESTAMP) AS DATE) AS DT_UP
    FROM CBM_PRPCI p JOIN CBM_ARQUIVO a ON a.NRO_INT_ARQUIVO = p.NRO_INT_ARQUIVO
    WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = p.NRO_INT_LICENCIAMENTO)
    UNION ALL
    SELECT a.NRO_INT_ARQUIVO,
           SUBSTR(COALESCE(a.NOME_ARQUIVO, 'sem-nome'), 1, 500),
           SUBSTR(a.TXT_IDENTIFICADOR_ALFRESCO, 1, 500),
           'APPCI', ap.NRO_INT_LICENCIAMENTO,
           CAST(COALESCE(a.CTR_DTH_INC, SYSTIMESTAMP) AS DATE)
    FROM CBM_APPCI ap JOIN CBM_ARQUIVO a ON a.NRO_INT_ARQUIVO = ap.NRO_INT_ARQUIVO
    WHERE EXISTS (SELECT 1 FROM SOL.LICENCIAMENTO l WHERE l.ID_LICENCIAMENTO = ap.NRO_INT_LICENCIAMENTO)
) src
WHERE NOT EXISTS (SELECT 1 FROM SOL.ARQUIVO_ED ae WHERE ae.ID_ARQUIVO_ED = src.NRO_INT_ARQUIVO);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.ARQUIVO_ED; DBMS_OUTPUT.PUT_LINE('ARQUIVO_ED inserido: ' || v); END;
/

-- ============================================================
-- PASSO 8 — ROTINA_EXECUCAO (0=EM_EXECUCAO 1=CONCLUIDA 2=ERRO)
-- ============================================================
PROMPT === PASSO 8: Migrando ROTINA_EXECUCAO ===
INSERT INTO SOL.ROTINA_EXECUCAO (
    ID_ROTINA_EXECUCAO, TIPO_ROTINA,
    DTH_INICIO_EXECUCAO, DTH_FIM_EXECUCAO,
    DSC_SITUACAO, NR_ERROS, DSC_MENSAGEM_ERRO, DTH_CRIACAO
)
SELECT
    r.NRO_INT_ROTINA,
    SUBSTR(COALESCE(r.TXT_ROTINA, 'ROTINA'), 1, 60),
    r.DTH_INICIO, r.DTH_FIM,
    CASE r.TP_SITUACAO WHEN 0 THEN 'EM_EXECUCAO' WHEN 1 THEN 'CONCLUIDA'
                       WHEN 2 THEN 'ERRO' ELSE 'CONCLUIDA' END,
    0,
    SUBSTR(r.TXT_ERRO, 1, 2000),
    CAST(COALESCE(r.CTR_DTH_INC, SYSTIMESTAMP) AS DATE)
FROM CBM_ROTINA r
WHERE NOT EXISTS (SELECT 1 FROM SOL.ROTINA_EXECUCAO re WHERE re.ID_ROTINA_EXECUCAO = r.NRO_INT_ROTINA);

DECLARE v NUMBER; BEGIN SELECT COUNT(*) INTO v FROM SOL.ROTINA_EXECUCAO; DBMS_OUTPUT.PUT_LINE('ROTINA_EXECUCAO inserido: ' || v); END;
/

-- ============================================================
-- PASSO 9 — Atualizar sequences
-- ============================================================
PROMPT === PASSO 9: Atualizando sequences ===
DECLARE v NUMBER; BEGIN
  SELECT NVL(MAX(ID_USUARIO),0)        +1000 INTO v FROM SOL.USUARIO;        EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_USUARIO RESTART START WITH '        ||v; DBMS_OUTPUT.PUT_LINE('SEQ_USUARIO → '        ||v);
  SELECT NVL(MAX(ID_ENDERECO),0)       +1000 INTO v FROM SOL.ENDERECO;       EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_ENDERECO RESTART START WITH '       ||v; DBMS_OUTPUT.PUT_LINE('SEQ_ENDERECO → '       ||v);
  SELECT NVL(MAX(ID_LICENCIAMENTO),0)  +1000 INTO v FROM SOL.LICENCIAMENTO;  EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_LICENCIAMENTO RESTART START WITH '  ||v; DBMS_OUTPUT.PUT_LINE('SEQ_LICENCIAMENTO → '  ||v);
  SELECT NVL(MAX(ID_BOLETO),0)         +1000 INTO v FROM SOL.BOLETO;         EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_BOLETO RESTART START WITH '         ||v; DBMS_OUTPUT.PUT_LINE('SEQ_BOLETO → '         ||v);
  SELECT NVL(MAX(ID_MARCO_PROCESSO),0) +1000 INTO v FROM SOL.MARCO_PROCESSO; EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_MARCO_PROCESSO RESTART START WITH ' ||v; DBMS_OUTPUT.PUT_LINE('SEQ_MARCO_PROCESSO → ' ||v);
  SELECT NVL(MAX(ID_ARQUIVO_ED),0)     +1000 INTO v FROM SOL.ARQUIVO_ED;     EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_ARQUIVO_ED RESTART START WITH '     ||v; DBMS_OUTPUT.PUT_LINE('SEQ_ARQUIVO_ED → '     ||v);
  SELECT NVL(MAX(ID_ROTINA_EXECUCAO),0)+1000 INTO v FROM SOL.ROTINA_EXECUCAO;EXECUTE IMMEDIATE 'ALTER SEQUENCE SOL.SEQ_ROTINA_EXECUCAO RESTART START WITH '||v; DBMS_OUTPUT.PUT_LINE('SEQ_ROTINA_EXECUCAO → '||v);
END;
/

-- ============================================================
-- PASSO 10 — Validação final
-- ============================================================
PROMPT === PASSO 10: Contagem final ===
SELECT 'SOL.USUARIO'         AS TABELA, COUNT(*) AS MIGRADOS FROM SOL.USUARIO         UNION ALL
SELECT 'SOL.ENDERECO',                  COUNT(*)             FROM SOL.ENDERECO         UNION ALL
SELECT 'SOL.LICENCIAMENTO',             COUNT(*)             FROM SOL.LICENCIAMENTO    UNION ALL
SELECT 'SOL.BOLETO',                    COUNT(*)             FROM SOL.BOLETO           UNION ALL
SELECT 'SOL.MARCO_PROCESSO',            COUNT(*)             FROM SOL.MARCO_PROCESSO   UNION ALL
SELECT 'SOL.ARQUIVO_ED',                COUNT(*)             FROM SOL.ARQUIVO_ED       UNION ALL
SELECT 'SOL.ROTINA_EXECUCAO',           COUNT(*)             FROM SOL.ROTINA_EXECUCAO;

PROMPT
PROMPT === Revise os contadores acima. Descomente o COMMIT quando satisfeito. ===
-- COMMIT;
EXIT;
