package br.gov.rs.cbm.sol.entity.enums;

public enum StatusLicenciamento {
    RASCUNHO,
    ANALISE_PENDENTE,
    EM_ANALISE,
    CIA_EMITIDO,
    CIA_CIENCIA,
    DEFERIDO,
    INDEFERIDO,
    VISTORIA_PENDENTE,
    EM_VISTORIA,
    CIV_EMITIDO,
    CIV_CIENCIA,
    PRPCI_EMITIDO,
    APPCI_EMITIDO,
    ALVARA_VENCIDO,
    // P14 - Renovacao
    AGUARDANDO_ACEITE_RENOVACAO,
    AGUARDANDO_PAGAMENTO_RENOVACAO,
    AGUARDANDO_DISTRIBUICAO_RENOV,
    EM_VISTORIA_RENOVACAO,
    // P10 - Recurso
    RECURSO_PENDENTE,
    EM_RECURSO,
    SUSPENSO,
    EXTINTO,
    RENOVADO
}
