package br.gov.rs.cbm.sol.entity.enums;

public enum TipoMarco {
    // P03 - Submissao
    SUBMISSAO,
    RASCUNHO_SALVO,

    // P04 - Analise Tecnica
    DISTRIBUICAO,
    INICIO_ANALISE,
    CIA_EMITIDO,
    CIA_CIENCIA,
    APROVACAO_ANALISE,
    REPROVACAO_ANALISE,

    // P05 - Ciencia Recurso
    CIENCIA_RECURSO,

    // P06 - Isencao Taxa
    ISENCAO_SOLICITADA,
    ISENCAO_DEFERIDA,
    ISENCAO_INDEFERIDA,

    // P07 - Vistoria
    VISTORIA_AGENDADA,
    VISTORIA_REALIZADA,
    CIV_EMITIDO,
    CIV_CIENCIA,
    VISTORIA_APROVADA,
    VISTORIA_REPROVADA,

    // P08 - PRPCI / APPCI
    PRPCI_EMITIDO,
    APPCI_EMITIDO,

    // P09 - Troca Envolvidos
    TROCA_RT_SOLICITADA,
    TROCA_RT_AUTORIZADA,
    TROCA_RT_EFETIVADA,
    TROCA_RU_EFETIVADA,

    // P10 - Recurso
    RECURSO_INTERPOSTO,
    RECURSO_EM_ANALISE,
    RECURSO_DEFERIDO,
    RECURSO_INDEFERIDO,

    // P11 - Pagamento
    BOLETO_GERADO,
    PAGAMENTO_CONFIRMADO,
    BOLETO_VENCIDO,
    BOLETO_CANCELADO,

    // P12 - Extincao
    EXTINCAO_SOLICITADA,
    EXTINCAO_EFETIVADA,

    // P13 - Jobs
    SUSPENSAO_AUTOMATICA,
    CANCELAMENTO_AUTOMATICO,
    NOTIFICACAO_SOLICITAR_RENOVACAO_90,
    NOTIFICACAO_SOLIC_RENOV_PRAZO_VENCIDO_59,
    NOTIFICACAO_SOLIC_RENOV_PRAZO_VENCIDO_29,
    NOTIFICACAO_ALVARA_VENCIDO,

    // P14 - Renovacao
    INICIO_RENOVACAO,
    ACEITE_ANEXOD_RENOVACAO,
    REMOCAO_ACEITE_ANEXOD_RENOVACAO,
    SOLICITACAO_ISENCAO_RENOVACAO,
    ANALISE_ISENCAO_RENOV_APROVADO,
    ANALISE_ISENCAO_RENOV_REPROVADO,
    BOLETO_VISTORIA_RENOVACAO_PPCI,
    LIQUIDACAO_VISTORIA_RENOVACAO,
    DISTRIBUICAO_VISTORIA_RENOV,
    ENVIO_VISTORIA_RENOVACAO,
    ACEITE_VISTORIA_RENOVACAO,
    FIM_ACEITES_VISTORIA_RENOVACAO,
    VISTORIA_RENOVACAO,
    VISTORIA_RENOVACAO_CIV,
    HOMOLOG_VISTORIA_RENOV_DEFERIDO,
    HOMOLOG_VISTORIA_RENOV_INDEFERIDO,
    CIENCIA_APPCI_RENOVACAO,
    CIENCIA_CIV_RENOVACAO,
    LIBERACAO_RENOV_APPCI,
    EMISSAO_DOC_COMPLEMENTAR_RENOV,
    RENOVACAO_CONCLUIDA,
    RENOVACAO_CANCELADA
}
